# Generated by Django 6.0.6 on 2026-06-15 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(help_text='ユーザーが学習対象としている資格名 (例: 応用情報技術者, 基本情報技術者)', max_length=255, verbose_name='資格名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='ステータス')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sessions_status_fb16d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='つまずきポイント、理解度、アドバイスの要点をまとめたMarkdownテキスト', verbose_name='最新要約テキスト(Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.session', verbose_name='セッション')),
            ],
            options={
                'db_table': 'session_summaries',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, verbose_name='送信者ロール')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('content', models.TextField(verbose_name='メッセージ本文')),
                ('rating', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='評価')),
                ('progress_status', models.TextField(blank=True, help_text='AIが判断した学習進捗や理解の深まり具合', null=True, verbose_name='進捗状況')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.session', verbose_name='セッション')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['session', 'sent_at'], name='messages_session_ac789d_idx')],
            },
        ),
    ]
